apiVersion: batch/v1
kind: Job
metadata:
  name: compute
  namespace: jobs
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    metadata:
      labels:
        job-name: compute
    spec:
      restartPolicy: Never
      containers:
        - name: compute
          image: python:3.11-slim
          command: ["python", "-c"]
          args:
            - |
              import time, math
              print("=== Starting Computation ===")
              print("Iterations:", {{ values.iterations }})
              start = time.time()
              result = sum(math.sqrt(i) for i in range({{ values.iterations }}))
              duration = time.time() - start
              print("=== Results ===")
              print(f"Sum: {result:,.2f}")
              print(f"Duration: {duration:.4f}s")
              print(f"Rate: {int({{ values.iterations }} / duration):,} ops/sec")
          resources:
            requests:
              cpu: {{ values.cpu }}
              memory: {{ values.memory }}
