# ArgoCD Project for Platform Team (Full Access)
# Platform engineers can deploy to any namespace and manage infrastructure
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-team
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Platform Team - Full access to infrastructure and apps
  
  # Source repositories the project can deploy from
  sourceRepos:
  - '*'  # Allow any repo for platform team
  
  # Destinations - where apps can be deployed
  destinations:
  - namespace: '*'
    server: '*'  # Allow any cluster for platform team
  
  # Cluster resource whitelist - what K8s resources can be created
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # Roles - map to RBAC policies
  roles:
  - name: platform-admin
    description: Full access for platform engineering team
    policies:
    - p, proj:platform-team:platform-admin, applications, *, platform/*, allow
    - p, proj:platform-team:platform-admin, clusters, *, *, allow
    - p, proj:platform-team:platform-admin, repositories, *, *, allow
    - p, proj:platform-team:platform-admin, logs, get, *, allow
    - p, proj:platform-team:platform-admin, exec, create, */*, allow
    groups:
    - platform-team  # Google Group or IAM group
