apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: proxima-templates
  description: ML Platform Templates
spec:
  type: url
  targets:
    - ./submit-job.yaml
    - ./test-compute.yaml
    - ./automate-compute.yaml
    # Add more templates here:
    # - ./create-pipeline.yaml
    # - ./deploy-model.yaml
    # - ./train-model.yaml
