apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: run-compute
  title: Run Compute Job
  description: Execute a computation on the workload cluster
  tags:
    - compute
    - test
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Job Configuration
      required:
        - iterations
      properties:
        iterations:
          title: Iterations
          type: number
          description: Number of sqrt calculations
          default: 1000000
        cpu:
          title: CPU Request
          type: string
          description: CPU allocation (e.g., 100m, 500m)
          default: "100m"
        memory:
          title: Memory Request
          type: string
          description: Memory allocation (e.g., 128Mi, 256Mi)
          default: "128Mi"

  steps:
    - id: generate-job-name
      name: Generate Job Name
      action: debug:log
      input:
        message: "Creating compute job with ${{ parameters.iterations }} iterations"

  output:
    text:
      - title: "Step 1: Run This Command"
        content: |
          Switch to workload cluster and create the job:
          ```bash
          kubectl config use-context workload
          kubectl create -f - <<'EOF'
          apiVersion: batch/v1
          kind: Job
          metadata:
            generateName: compute-
            namespace: jobs
          spec:
            ttlSecondsAfterFinished: 300
            template:
              spec:
                restartPolicy: Never
                containers:
                - name: compute
                  image: python:3.11-slim
                  command: ["python", "-c"]
                  args:
                    - |
                      import time, math
                      print("=== Starting Computation ===")
                      print(f"Iterations: ${{ parameters.iterations }}")
                      start = time.time()
                      result = sum(math.sqrt(i) for i in range(${{ parameters.iterations }}))
                      duration = time.time() - start
                      print(f"\n=== Results ===")
                      print(f"Sum: {result:,.2f}")
                      print(f"Duration: {duration:.4f}s")
                      print(f"Rate: {${{ parameters.iterations }}/duration:,.0f} ops/sec")
                  resources:
                    requests:
                      cpu: "${{ parameters.cpu }}"
                      memory: "${{ parameters.memory }}"
          EOF
          ```

      - title: "Step 2: Check Results"
        content: |
          View the latest job results automatically:
          ```bash
          # Get the most recent compute job logs
          kubectl logs -n jobs $(kubectl get pods -n jobs -l job-name --sort-by=.metadata.creationTimestamp -o name | grep compute | tail -1)
          ```
          
          Or check all recent compute jobs:
          ```bash
          kubectl get jobs -n jobs --sort-by=.metadata.creationTimestamp | grep compute | tail -5
          ```

      - title: "Quick Check"
        content: |
          Get latest job logs:
          ```bash
          kubectl logs -n jobs $(kubectl get pods -n jobs --sort-by=.metadata.creationTimestamp -o name | tail -1)
          ```
